name: btc_map
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.10.0
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.3.6
  location: ^5.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/markers/base_marker.png